Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TransporteWeb.Models;

namespace TransporteWeb.Controllers
{
    [Authorize(Roles = "Funcionario")]
    public class CursosController : Controller
    {
        private readonly Contexto _context;

        public CursosController(Contexto context)
        {
            _context = context;
        }

        // GET: Cursos
        public async Task<IActionResult> Index(string searchString, int? page, int pageSize = 10)
        {
            int pageNumber = page ?? 1;  // Se o número da página não for fornecido, default é 1.
            var cursos = from c in _context.Cursos
                         select c;

            // Aplica o filtro de busca
            if (!String.IsNullOrEmpty(searchString))
            {
                cursos = cursos.Where(c => c.nome.Contains(searchString));
            }

            int totalItems = await cursos.CountAsync(); // Conta o total de itens após o filtro.

            // Aplica a paginação
            var cursosPaginados = await cursos
                .OrderBy(c => c.nome) // Ordena os cursos por nome.
                .Skip((pageNumber - 1) * pageSize) // Pula os registros das páginas anteriores.
                .Take(pageSize) // Pega o número de registros da página atual.
                .ToListAsync();

            // Passa o número de páginas e outros dados para a View
            ViewBag.CurrentPage = pageNumber;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            ViewBag.SearchString = searchString;

            return View(cursosPaginados);
        }

        // GET: Cursos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cursos == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos
                .FirstOrDefaultAsync(m => m.id == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // GET: Cursos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cursos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nome")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                _context.Add(curso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: Cursos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cursos == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos.FindAsync(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        // POST: Cursos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome")] Curso curso)
        {
            if (id != curso.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: Cursos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cursos == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos
                .FirstOrDefaultAsync(m => m.id == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // POST: Cursos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cursos == null)
            {
                return Problem("Entity set 'Contexto.Cursos'  is null.");
            }
            var curso = await _context.Cursos.FindAsync(id);
            if (curso != null)
            {
                _context.Cursos.Remove(curso);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CursoExists(int id)
        {
            return _context.Cursos.Any(e => e.id == id);
        }
    }
}

Controllers/PontosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TransporteWeb.Models;

namespace TransporteWeb.Controllers
{
    [Authorize(Roles = "Funcionario")]
    public class PontosController : Controller
    {
        private readonly Contexto _context;

        public PontosController(Contexto context)
        {
            _context = context;
        }

        // GET: Pontos
        public async Task<IActionResult> Index(string searchString, int? page, int pageSize = 10)
        {
            int pageNumber = page ?? 1;  // Se o número da página não for fornecido, default é 1.
            var pontos = from p in _context.Pontos
                         select p;

            // Aplica o filtro de busca
            if (!String.IsNullOrEmpty(searchString))
            {
                pontos = pontos.Where(p => p.nomeponto.Contains(searchString));
            }

            int totalItems = await pontos.CountAsync(); // Conta o total de itens após o filtro.

            // Aplica a paginação
            var pontosPaginados = await pontos
                .OrderBy(p => p.nomeponto) // Ordena os pontos por nome.
                .Skip((pageNumber - 1) * pageSize) // Pula os registros das páginas anteriores.
                .Take(pageSize) // Pega o número de registros da página atual.
                .ToListAsync();

            // Passa o número de páginas e outros dados para a View
            ViewBag.CurrentPage = pageNumber;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            ViewBag.SearchString = searchString;

            return View(pontosPaginados);
        }

        // GET: Pontos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pontos == null)
            {
                return NotFound();
            }

            var ponto = await _context.Pontos
                .FirstOrDefaultAsync(m => m.id == id);
            if (ponto == null)
            {
                return NotFound();
            }

            return View(ponto);
        }

        // GET: Pontos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pontos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nomeponto")] Ponto ponto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ponto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ponto);
        }

        // GET: Pontos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pontos == null)
            {
                return NotFound();
            }

            var ponto = await _context.Pontos.FindAsync(id);
            if (ponto == null)
            {
                return NotFound();
            }
            return View(ponto);
        }

        // POST: Pontos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nomeponto")] Ponto ponto)
        {
            if (id != ponto.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ponto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PontoExists(ponto.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ponto);
        }

        // GET: Pontos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pontos == null)
            {
                return NotFound();
            }

            var ponto = await _context.Pontos
                .FirstOrDefaultAsync(m => m.id == id);
            if (ponto == null)
            {
                return NotFound();
            }

            return View(ponto);
        }

        // POST: Pontos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pontos == null)
            {
                return Problem("Entity set 'Contexto.Pontos'  is null.");
            }
            var ponto = await _context.Pontos.FindAsync(id);
            if (ponto != null)
            {
                _context.Pontos.Remove(ponto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PontoExists(int id)
        {
            return _context.Pontos.Any(e => e.id == id);
        }
    }
}

Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TransporteWeb.Models;

namespace TransporteWeb.Controllers
{
    [Authorize(Roles = "Funcionario")]
    public class VeiculosController : Controller
    {
        private readonly Contexto _context;

        public VeiculosController(Contexto context)
        {
            _context = context;
        }

        // GET: Veiculos
        public async Task<IActionResult> Index(string searchString, int page = 1)
        {
            var veiculos = from v in _context.Veiculos select v; // Query inicial

            // Aplicar busca
            if (!string.IsNullOrEmpty(searchString))
            {
                veiculos = veiculos.Where(v => v.nomeveiculo.Contains(searchString)); // Ajuste conforme necessário
            }

            // Configuração de paginação
            int pageSize = 10; // Defina o tamanho da página
            ViewBag.TotalPages = Math.Ceiling(await veiculos.CountAsync() / (double)pageSize);
            ViewBag.CurrentPage = page;
            var pagedVeiculos = await veiculos.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            ViewBag.SearchString = searchString; // Passa a string de busca para a View
            return View(pagedVeiculos);
        }

        // GET: Veiculos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Veiculos == null)
            {
                return NotFound();
            }

            var veiculo = await _context.Veiculos
                .FirstOrDefaultAsync(m => m.id == id);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        // GET: Veiculos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Veiculos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nomeveiculo,placa,vagas")] Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(veiculo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(veiculo);
        }

        // GET: Veiculos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Veiculos == null)
            {
                return NotFound();
            }

            var veiculo = await _context.Veiculos.FindAsync(id);
            if (veiculo == null)
            {
                return NotFound();
            }
            return View(veiculo);
        }

        // POST: Veiculos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nomeveiculo,placa,vagas")] Veiculo veiculo)
        {
            if (id != veiculo.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(veiculo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VeiculoExists(veiculo.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(veiculo);
        }

        // GET: Veiculos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Veiculos == null)
            {
                return NotFound();
            }

            var veiculo = await _context.Veiculos
                .FirstOrDefaultAsync(m => m.id == id);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        // POST: Veiculos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Veiculos == null)
            {
                return Problem("Entity set 'Contexto.Veiculos'  is null.");
            }
            var veiculo = await _context.Veiculos.FindAsync(id);
            if (veiculo != null)
            {
                _context.Veiculos.Remove(veiculo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VeiculoExists(int id)
        {
            return _context.Veiculos.Any(e => e.id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Transporte</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Transporte.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark text-light">
    <header class="bg-dark text-light shadow-sm">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/aeta-removebg-preview.png" alt="Logo" width="60" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                         @if(User.IsInRole("Funcionario"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        
                       
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Funcionario
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Veiculos" asp-action="Index">Veículos</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Estudantes" asp-action="Index">Estudantes</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Index">Agendamentos</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Pontos" asp-action="Index">Pontos de Embarque</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Pagamentos
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="PagamentoMultas" asp-action="Lista">Lista de Pagamentos</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="PagamentoMultas" asp-action="EstudantesComMulta">Cobranca</a></li>

                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                                </ul>
                            </li>
                            
                        }
                        @if (User.IsInRole("Motorista"))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Motorista
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Motoristas" asp-action="index">Agendamentos</a></li>
     
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                            </ul>
                        </li>
                        }
                        @if (User.IsInRole("Estudante"))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Agendamento
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Create">Agendar</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Index">Meus Agendamentos</a></li>

                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                            </ul>
                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark text-light border-top py-3 mt-auto">
        <div class="container text-center">
            &copy; 2024 - Sistema de Transporte | Todos os direitos reservados.
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>